apiVersion: 1

datasources:
  - name: Tempo
    uid: P214B5B846CF3925F
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: Prometheus
      serviceMap:
        datasourceUid: Prometheus
