const $=id=>document.getElementById(id), state={logs:[]};
const base=()=>($('baseUrl').value||'').replace(/\/$/,'');
function headers(admin=true){const h={'Content-Type':'application/json'};if(admin)h['X-Config-Admin-Key']=$('adminKey').value;if($('actorId').value)h['X-Actor-Id']=$('actorId').value;return h}
async function api(method,path,body,admin=true){const started=performance.now(),url=base()+path;let response,data;try{response=await fetch(url,{method,headers:headers(admin),body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();try{data=text?JSON.parse(text):null}catch{data=text}log(method,path,response.status,performance.now()-started,body,data);if(!response.ok)throw new Error(typeof data==='string'?data:(data?.message||`HTTP ${response.status}`));return data}catch(error){if(!response)log(method,path,'ERR',performance.now()-started,body,error.message);throw error}}
function log(method,path,status,duration,request,response){state.logs.unshift({method,path,status,duration:Math.round(duration),request,response});$('logCount').textContent=state.logs.length;renderLogs()}
function renderLogs(){const box=$('apiLog');box.classList.remove('empty');box.innerHTML=state.logs.length?state.logs.map(x=>`<div class="log-row"><div class="log-meta"><strong>${x.method} ${x.path}</strong><span class="${String(x.status).startsWith('2')?'status-ok':'status-fail'}">${x.status} · ${x.duration}ms</span></div><div class="log-body">request: ${pretty(x.request)}\nresponse: ${pretty(x.response)}</div></div>`).join(''):'Chưa có request.'}
const pretty=x=>x==null?'—':typeof x==='string'?x:JSON.stringify(x,null,2);
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function entries(){return Object.fromEntries($('configEntries').value.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return[i<0?x:x.slice(0,i),i<0?'':x.slice(i+1)]}))}
async function run(action,success='Hoàn tất'){try{const data=await action();toast(success);return data}catch(e){toast(e.message);}}
async function loadDraft(){const a=$('configApp').value,p=$('configProfile').value;const data=await api('GET',`/config/v1/apps/${encodeURIComponent(a)}/profiles/${encodeURIComponent(p)}/draft`);$('configEntries').value=(Array.isArray(data)?data:data?.data||[]).map(x=>`${x.key}=${x.value}`).join('\n');$('configOutput').textContent=pretty(data)}
async function loadSnapshot(){const a=$('configApp').value,p=$('configProfile').value;const data=await api('GET',`/config/v1/apps/${encodeURIComponent(a)}/profiles/${encodeURIComponent(p)}` ,undefined,false);$('configOutput').textContent=pretty(data)}
function configPath(suffix=''){return`/config/v1/apps/${encodeURIComponent($('configApp').value)}/profiles/${encodeURIComponent($('configProfile').value)}${suffix}`}
$('saveDraftBtn').onclick=()=>run(()=>api('POST',configPath('/draft'),{entries:entries()}),'Đã lưu draft');$('loadDraftBtn').onclick=()=>run(loadDraft);$('loadDraftBtn2').onclick=()=>run(loadDraft);$('loadSnapshotBtn').onclick=()=>run(loadSnapshot);
$('publishBtn').onclick=()=>run(()=>api('POST',configPath('/publish')),'Đã publish');$('publishKeysBtn').onclick=()=>run(()=>api('POST',configPath('/publish/keys'),{keys:$('publishKeys').value.split(',').map(x=>x.trim()).filter(Boolean)}),'Đã publish các key');$('rollbackBtn').onclick=()=>run(()=>api('POST',configPath(`/rollback/${$('rollbackVersion').value}`)),'Đã rollback');$('auditBtn').onclick=()=>run(async()=>{$('configOutput').textContent=pretty(await api('GET',configPath('/audit')))},'Đã tải audit');
function bindForm(id,path,fields,success){$(id).onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),body={};fields.forEach(k=>{const v=f.get(k);if(v!==''&&v!=null)body[k]=k==='parentId'?Number(v):v});return run(()=>api('POST',path,body),success)}}
bindForm('operationForm','/entitlements/admin/operations',['code','name','domain'],'Đã tạo operation');bindForm('groupForm','/entitlements/admin/groups',['code','name','parentId'],'Đã tạo group');bindForm('packageForm','/entitlements/admin/service-packages',['code','name'],'Đã tạo service package');
async function loadCatalog(){const [operations,groups,packages]=await Promise.all([api('GET','/entitlements/admin/operations'),api('GET','/entitlements/admin/groups'),api('GET','/entitlements/admin/service-packages')]);const unwrap=value=>Array.isArray(value)?value:(value?.data||[]);const data={operations:unwrap(operations),groups:unwrap(groups),packages:unwrap(packages)};document.querySelectorAll('select[data-catalog]').forEach(select=>{const items=data[select.dataset.catalog]||[];select.innerHTML='<option value="">Chọn một giá trị</option>'+items.map(item=>`<option value="${item.id}">${item.code} · ${item.name} (#${item.id})</option>`).join('')});return data}
$('loadCatalogBtn').onclick=()=>run(loadCatalog,'Đã tải catalog entitlement');
setTimeout(()=>run(loadCatalog,'Đã tải catalog entitlement'),0);
function bindBindingForm(id,path,fields,success){$(id).onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const values=Object.fromEntries(fields.map(k=>[k,f.get(k)]));const suffix=path(values);return run(()=>api('POST',suffix,undefined),'Đã cập nhật entitlement')}}
bindBindingForm('groupOperationForm',v=>`/entitlements/admin/groups/${v.groupId}/operations/${v.operationId}?effect=${encodeURIComponent(v.effect)}`,['groupId','operationId','effect'],'Đã gắn operation vào group');
bindBindingForm('packageGroupForm',v=>`/entitlements/admin/service-packages/${v.packageId}/groups/${v.groupId}?effect=${encodeURIComponent(v.effect)}`,['packageId','groupId','effect'],'Đã gắn group vào package');
$('customerPackageForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);return run(()=>api('POST',`/entitlements/admin/customers/${encodeURIComponent(f.get('customerId'))}/service-packages/${f.get('packageId')}`,{effectiveFrom:null,effectiveTo:null}),'Đã gán package cho customer')};
$('loadEntitlementBtn').onclick=()=>run(async()=>{$('entitlementOutput').textContent=pretty(await api('GET',`/entitlements/subjects/${encodeURIComponent($('subjectType').value)}/${encodeURIComponent($('subjectId').value)}`,undefined,false))},'Đã tải snapshot');$('snapshotForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);return run(()=>api('POST',`/entitlements/subjects/${encodeURIComponent($('subjectType').value)}/${encodeURIComponent($('subjectId').value)}`,{allow:f.get('allow').split(',').map(x=>x.trim()).filter(Boolean),deny:f.get('deny').split(',').map(x=>x.trim()).filter(Boolean),version:Date.now()}),'Đã lưu snapshot')};
$('overrideForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);return run(()=>api('POST',`/entitlements/admin/subjects/${encodeURIComponent(f.get('type'))}/${encodeURIComponent(f.get('id'))}/overrides`,{operationId:Number(f.get('operationId')),effect:f.get('effect'),reason:f.get('reason'),effectiveFrom:null,effectiveTo:null}),'Đã lưu override')};
$('healthBtn').onclick=()=>run(async()=>{await fetch(base()+'/actuator/health').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()});$('healthDot').className='dot ok';$('healthText').textContent='Common đang hoạt động';toast('Kết nối thành công')},'Kết nối thành công').catch(()=>{$('healthDot').className='dot bad';$('healthText').textContent='Không kết nối được'});$('clearLogBtn').onclick=()=>{state.logs.length=0;$('logCount').textContent=0;renderLogs()};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.tab-content').forEach(x=>x.classList.remove('active'));t.classList.add('active');$(t.dataset.tab).classList.add('active')});
